{% set version = "2.1.1" %}

package:
  name: cf-units
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cf-units/cf-units-{{ version }}.tar.gz
  sha256: fa0ef8efd84546e61088aa23e76ebbaf7043167dc3a7f35f34549c234b543530

build:
  number: 1000

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - udunits2
    # It isn't clear that this really is needed, but it is listed in setup.py.
    - pytest-runner
  run:
    - {{ pin_compatible('udunits2', max_pin='x.x') }}
    - python
    - cftime
    - {{ pin_compatible('numpy') }}
    - antlr-python-runtime 4.7.2.*  # [py3k]
    - six

test:
  requires:
    - pytest
  imports:
    - cf_units
  commands:
    - pytest --pyargs cf_units                                   # [not (win and py2k)]
      # On win py2 we are getting an unexpected test failure. See also
      # https://github.com/SciTools/cf-units/issues/148.
    - pytest --pyargs cf_units -k="-test_read_xml_invalid_path"  # [win and py2k]

about:
  home: https://scitools.org.uk/cf-units/docs/latest/
  license: LGPL-3.0
  license_file: COPYING.LESSER
  summary: 'Units of measure as required by the Climate and Forecast (CF) metadata conventions.'

extra:
  recipe-maintainers:
    - bjlittle
    - ocefpaf
    - pelson
